kinolist/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^person/(?P<person_id>[0-9]+)/$', views.person, name='person'),
    url(r'^movie/(?P<movie_id>[0-9]+)/$', views.movie, name='movie'),
    url(r'^movies/$', views.movies, name='movies'),
    url(r'^people/$', views.people, name='people'),
    url(r'^user/$', views.user, name='user'),
    url(r'^auth/$', views.auth, name='auth'),
]

polls/models.py
from django.db import models
from django.db.models import Avg

class Person(models.Model):
    name = models.CharField(max_length=50)
    second_name = models.CharField(max_length=50)
    birthday = models.DateField()
    country = models.CharField(max_length=50)
    def __str__(self):
        return self.name + " " + self.second_name

class User(models.Model):
    login = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    def __str__(self):
        return self.login + " " + self.email

class Movie(models.Model):
    name = models.CharField(max_length=50)
    genre = models.CharField(max_length=50)
    time = models.IntegerField(default=0)
    year = models.IntegerField(default=0)
    def __str__(self):
        return self.name
    def user_avg(self):
        return UserMovie.objects.filter(idmovie=self).aggregate(Avg('mark'))['mark__avg']

class PersonMovie(models.Model):
    idactor = models.ForeignKey(Person, on_delete=models.CASCADE)
    idmovie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    role = models.CharField(max_length=50)
    def __str__(self):
        return self.idactor.name + " " + self.idactor.second_name + " " + self.idmovie.name

class UserMovie(models.Model):
    iduser = models.ForeignKey(User, on_delete=models.CASCADE)
    idmovie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    mark = models.IntegerField(default=0)
    def __str__(self):
        return self.iduser.login + " " + self.iduser.email + " " + self.idmovie.name

polls/views.py
from django.shortcuts import get_object_or_404, render

from .models import Movie, Person, User, PersonMovie, UserMovie

def index(request):
    latest_movie_list = Movie.objects.order_by('-id')[:3]
    context = {'latest_movie_list': latest_movie_list}
    return render(request, 'polls/index.html', context)

def movies(request):
    movie_list = Movie.objects.all()
    context = {'movie_list': movie_list}
    return render(request, 'polls/movies.html', context)

def people(request):
    people_list = Person.objects.all()
    context = {'people_list': people_list}
    return render(request, 'polls/people.html', context)

def person(request, person_id):
    person = get_object_or_404(Person, pk=person_id)
    return render(request, 'polls/person.html', {'person': person})

def movie(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    return render(request, 'polls/movie.html', {'movie': movie})

def user(request):
    user = get_object_or_404(User, login=request.POST['param1'], password=request.POST['param2'])
    movie_list = Movie.objects.all()
    return render(request, 'polls/user.html', {'user': user, 'movie_list':movie_list})

def user(request):
    if request.POST.get('param1') and request.POST.get('param2'):
        user = get_object_or_404(User, login=request.POST['param1'], password=request.POST['param2'])
    if request.POST.get('param3'):
        movie = get_object_or_404(Movie, name=request.POST['param3'])
    if request.POST.get('param4'):
        q = UserMovie.objects.create(iduser=user, idmovie=movie, mark=request.POST['param4'])
    movie_list = Movie.objects.all()
    return render(request, 'polls/user.html', {'user': user, 'movie_list':movie_list})

def auth(request):
    return render(request, 'polls/auth.html', {})

polls/templates/polls/auth.html
{% load staticfiles %}
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="" id="title">Кинолист</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/polls/">Главная</a></li>
      <li><a href="/polls/movies">Фильмы</a></li>
      <li><a href="/polls/people">Люди</a></li> 
    </ul>
	<ul class="nav navbar-nav navbar-right">
        <li><a href="/polls/auth">Войти</a></li> 
    </ul>
  </div>
</nav>
<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12">
	<form action="/polls/user/" method="post">
	    {% csrf_token %}
		<h4 class="text-center"> <strong> Логин: </strong>  <input type="text" name="param1"> </input> </h4>
		<h4 class="text-center"> <strong> Пароль: </strong>  <input type="password" name = "param2"> </input> </h4>
		<button type="submit" class="btn btn-default center-block">Войти</button>
	</form>
	</div>
</div>

polls/templates/polls/index.html
{% load staticfiles %}
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="" id="title">Кинолист</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="">Главная</a></li>
      <li><a href="/polls/movies">Фильмы</a></li>
      <li><a href="/polls/people">Люди</a></li> 
    </ul>
	<ul class="nav navbar-nav navbar-right">
        <li><a href="/polls/auth">Войти</a></li> 
    </ul>
  </div>
</nav>
<div class="row">
<div class="col-lg-12 col-md-12 col-sm-12">
<h2 class="text-center"> <strong> Последнее в кино </strong></h2>
<br>
{% if latest_movie_list %}
    {% for movie in latest_movie_list %}
    <div class="col-lg-4 col-md-4 col-sm-4">
        <img src="{% static 'polls/movieImg/' %}{{movie.id}}.jpg" class="center-block" width = 300, height = 400>
        <br>
        <a href="/polls/movie/{{ movie.id }}/"> <h4 class="text-center"> <strong> {{ movie.name }} </strong></h4> </a>        
    </div>
    {% endfor %}
{% else %}
    <p>No films</p>	
{% endif %}
</div>

polls/templates/polls/movie.html
{% load staticfiles %}
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="" id="title">Кинолист</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/polls/">Главная</a></li>
      <li><a href="/polls/movies">Фильмы</a></li>
      <li><a href="/polls/people">Люди</a></li> 
    </ul>
	<ul class="nav navbar-nav navbar-right">
        <li><a href="/polls/auth">Войти</a></li> 
    </ul>
  </div>
</nav>
<div class="row">
<div class="col-lg-12 col-md-12 col-sm-12">
    <h1 class="text-center">{{ movie.name }}</h1>
    <br>
    <div class="col-lg-4 col-md-4 col-sm-4">
	<h3 class="text-center"> <strong>О фильме</strong></h3>
	<br> 
    <h4 class="text-center"> <strong> Жанр: </strong> {{movie.genre}} </h4>
    <br>
    <h4 class="text-center"> <strong> Год: </strong> {{movie.year}} </h4>
    <br>
    <h4 class="text-center"> <strong> Продолжительность: </strong> {{movie.time}} минут </h4>
    <br>
    <h4 class="text-center"> <strong> Рейтинг: </strong> {{movie.user_avg}} </h4>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4">
    <h3 class="text-center"> <strong>Люди</strong></h3>
	<br> 
    {% for personmovie in movie.personmovie_set.all %}
            <h4>{{personmovie.role}}:</h4><a href="/polls/person/{{personmovie.idactor.id}}/"><h4>{{personmovie.idactor }}</h4></a>
    {% endfor %}    
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4">
    <img src="{% static 'polls/movieImg/' %}{{movie.id}}.jpg" class="center-block" width = 300, height = 450>
    </div>
</div>
</div>

polls/templates/polls/movies.html
{% load staticfiles %}
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="" id="title">Кинолист</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/polls/">Главная</a></li>
      <li class="active"><a href="/polls/movies">Фильмы</a></li>
      <li><a href="/polls/people">Люди</a></li> 
    </ul>
	<ul class="nav navbar-nav navbar-right">
        <li><a href="/polls/auth">Войти</a></li> 
    </ul>
  </div>
</nav>
<div class="row">
<div class="col-lg-12 col-md-12 col-sm-12">
{% if movie_list %}
    {% for movie in movie_list %}
    <div class="col-lg-4 col-md-4 col-sm-4">
        <img src="{% static 'polls/movieImg/' %}{{movie.id}}.jpg" class="center-block" width = 300, height = 400>
        <br>
        <a href="/polls/movie/{{ movie.id }}/"> <h4 class="text-center"> <strong> {{ movie.name }} </strong></h4> </a>        
    </div>
    {% endfor %}
{% else %}
    <p>No films</p>	
{% endif %}

polls/templates/polls/people.html
{% load staticfiles %}
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="" id="title">Кинолист</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/polls/">Главная</a></li>
      <li><a href="/polls/movies">Фильмы</a></li>
      <li class="active"><a href="/polls/people">Люди</a></li> 
    </ul>
	<ul class="nav navbar-nav navbar-right">
        <li><a href="/polls/auth">Войти</a></li> 
    </ul>
  </div>
</nav>
<div class="row">
<div class="col-lg-12 col-md-12 col-sm-12">
{% if people_list %}
    {% for people in people_list %}
    <div class="col-lg-3 col-md-3 col-sm-3">
        <img src="{% static 'polls/peopleImg/' %}{{people.id}}.jpg" class="center-block" width = 250, height = 350>
        <br>
        <a href="/polls/person/{{ people.id }}/"> <h4 class="text-center"> <strong> {{ people.name }} {{ people.second_name }} </strong></h4> </a>        
    </div>
    {% endfor %}
{% else %}
    <p>No films</p>	
{% endif %}

polls/templates/polls/person.html
{% load staticfiles %}
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="" id="title">Кинолист</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/polls/">Главная</a></li>
      <li><a href="/polls/movies">Фильмы</a></li>
      <li><a href="/polls/people">Люди</a></li> 
    </ul>
	<ul class="nav navbar-nav navbar-right">
        <li><a href="/polls/auth">Войти</a></li> 
    </ul>
  </div>
</nav>
<div class="row">
<div class="col-lg-12 col-md-12 col-sm-12">
    <h1 class="text-center">{{ person.name }} {{ person.second_name }}</h1>
    <br>
    <div class="col-lg-4 col-md-4 col-sm-4">
	<h3 class="text-center"> <strong>Об актере</strong></h3>
	<br> 
    <h4 class="text-center"> <strong> Имя: </strong> {{person.name}} </h4>
    <br>
    <h4 class="text-center"> <strong> Фамилия: </strong> {{person.second_name}} </h4>
    <br>
    <h4 class="text-center"> <strong> День рождения: </strong> {{person.birthday}} минут </h4>
    <br>
    <h4 class="text-center"> <strong> Страна: </strong> {{person.country}} </h4>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4">
    <h3 class="text-center"> <strong>Фильмы</strong></h3>
	<br> 
    {% for personmovie in person.personmovie_set.all %}
            <h4>{{personmovie.role}} фильма:</h4><a href="/polls/movie/{{personmovie.idmovie.id}}/"><h4>{{personmovie.idmovie }}</h4></a>
    {% endfor %}    
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4">
    <img src="{% static 'polls/peopleImg/' %}{{person.id}}.jpg" class="center-block" width = 300, height = 450>
    </div>
</div>

polls/templates/polls/user.html
{% load staticfiles %}
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="" id="title">Кинолист</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/polls/">Главная</a></li>
      <li><a href="/polls/movies">Фильмы</a></li>
      <li><a href="/polls/people">Люди</a></li> 
    </ul>
	<ul class="nav navbar-nav navbar-right">
        <li><a href="/polls/auth">Войти</a></li> 
    </ul>
  </div>
</nav>
<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12">
		<div class="col-lg-1 col-md-1 col-sm-1">
		</div>
		<div class="col-lg-7 col-md-7 col-sm-7">		
		<h4> <strong> Логин: </strong> {{user.login}} </h4>
		<h4> <strong> Почта: </strong> {{user.email}} </h4>		
		</div>
		<div class="col-lg-4 col-md-4 col-sm-4">
			<form action="/polls/user/" method="post">
				{% csrf_token %}
				<h4> <strong> Фильм: </strong>  
				<select type="text" name="param3"> </input> 
					{% if movie_list %}
						{% for movie in movie_list %}
							<option>{{movie.name}}</option>
						{% endfor %}
					{% endif %}
				</select>
				<h4> <strong> Оценка: </strong>  <input type="text" name = "param4"> </input> </h4>
				<input type="hidden" name = "param1" value={{user.login}}></input>
				<input type="hidden" name = "param2" value={{user.password}}></input>
				<button type="submit" class="btn btn-default center-block">Добавить</button>
			</form>
		</div>
		<br>
		<br>
		<br>
		<br>
		<h2 class="text-center"> <strong>Просмотренные фильмы</strong></h2>
		<br>
		<br>
		<div class="col-lg-2 col-md-2 col-sm-2">
		</div>
		<div class="col-lg-10 col-md-10 col-sm-10">		
		<br> 
		{% for usermovie in user.usermovie_set.all %}
				<h4><strong> Фильм: </strong><a href="/polls/movie/{{usermovie.idmovie.id}}/">{{usermovie.idmovie }}</a>  <strong>Оценка:</strong> {{usermovie.mark}} </h4>
		{% endfor %}    
		</div>
	</div>
</div>